spring:
  jpa:
    #전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    #테이블 생성 후에 data.sql 실행
    #애플리케이션을 실행할때 테이블을 생성하고 data.sql이 있으면 쿼리를 실행하도록 하는 옵션
    defer-datasource-initialization: true

  profiles:
    include: oauth


  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa

  h2:
    console:
      enabled: true



  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false


  mail:
    host: smtp.gmail.com
    port: 465
    username: iiojineee@gmail.com
    password: xxtgsorsbghvkqnu
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true

naver-cloud-sms:
  accessKey: "gBHVFkTXNquxkoV1Sa0y"
  secretKey: "HDAYZhH7FZAc0do9ADRIcrHv1LBozvwKfPmI5Ifs"
  serviceId: "ncp:sms:kr:315761739749:jinee_shop"
  senderPhone: "01044032571"



