spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodfit?serverTimezone=Asia/Seoul
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none

  #테이블 생성 후에 data.sql 실행
  #애플리케이션을 실행할때 테이블을 생성하고 data.sql이 있으면 쿼리를 실행하도록 하는 옵션
#  sql:
#    init:
#      mode: always
#
#    defer-datasource-initialization: true


  profiles:
    include:
      - oauth
      - sms
      - mail

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/MySQL?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    url: jdbc:h2:mem:testdb;
#    username: sa

#  h2:
#    console:
#      enabled: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

itemImgLocation: C:/foodfit
uploadPath: file:///C:/foodfit/



