spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: iiojineee@gmail.com
    password: xxtgsorsbghvkqnu
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true