spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 569462444462-4hov692o7t18k953afja1gh1ngnpfa29.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: JtJKDa1OLasfFyrOaA3X
            client-secret: F_36f2X6_L
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 08c66a269759a52c833902a640c7a8ab
            client-secret: XxJEKIgEXBxx60vTSOa3mIq4ziGHJkQZ
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id