INSERT INTO category (level, category_name, category_code) VALUES (1, '샐러드·과일','100')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '파스타 샐러드','100','101')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '닭가슴살 샐러드','100','102')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '샐러드 도시락','100','103')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '과일','100','104')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '샐러드 소스','100','105')
INSERT INTO category (level, category_name, category_code) VALUES (1, '닭가슴살','200')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '소세지','200','201')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '스테이크','200','202')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '미트볼','200','203')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '닭가슴살볼','200','204')
INSERT INTO category (level, category_name, category_code) VALUES (1, '다이어트 간편식','300')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '도시락','300','301')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '고구마','300','302')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '볶음밥·밥류','300','302')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '파스타·면류','300','303')
INSERT INTO category (level, category_name, category_code) VALUES (1, '냉장·밀키트','400')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '국·찌개·탕','400','401')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '육류','400','402')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '반찬','400','403')
INSERT INTO category (level, category_name, category_code) VALUES (1, '분식·야식','500')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '떡볶이','500','501')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '피자·치킨·만두','500','502')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '너겟·튀김류','500','503')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '볶음류','500','504')
INSERT INTO category (level, category_name, category_code) VALUES (1, '단백질·선식','600')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '단백질바','600','601')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '선식','600','602')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '프로틴쉐이크','600','603')
INSERT INTO category (level, category_name, category_code) VALUES (1, '유제품·시리얼','700')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '요거트','700','701')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '시리얼','700','702')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '두유','700','703')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '치즈·버터','700','704')
INSERT INTO category (level, category_name, category_code) VALUES (1, '디저트','800')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '베이커리','800','801')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '떡·한과','800','802')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '과자','800','803')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '아이스크림','800','804')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '젤리·초콜릿','800','805')
INSERT INTO category (level, category_name, category_code) VALUES (1, '음료','900')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '스무디','900','901')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '탄산음료','900','902')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '차','900','903')
INSERT INTO category (level, category_name, parent_code, category_code) VALUES (2, '주스','900','904')
